-- DDL
CREATE DATABASE IF NOT EXISTS `upskill`;

USE `upskill`;

DROP TABLE IF EXISTS `PAYMENT`;
DROP TABLE IF EXISTS `INCOME`;
DROP TABLE IF EXISTS `CARD`;
DROP TABLE IF EXISTS `CARDNETWORK`;
DROP TABLE IF EXISTS `ACCOUNT`;
DROP TABLE IF EXISTS `PERSON`;
DROP TABLE IF EXISTS `STATUS`;
DROP TABLE IF EXISTS `PERM`;

CREATE TABLE IF NOT EXISTS `PERM`
(
    `ID`       INTEGER,
    `NAME`     VARCHAR(10),
    PRIMARY KEY (`ID`)
    );

CREATE TABLE IF NOT EXISTS `STATUS`
(
    `ID`       INTEGER,
    `NAME`     VARCHAR(10),
    PRIMARY KEY (`ID`)
    );

CREATE TABLE IF NOT EXISTS `PERSON`
(
    `ID`         BIGINT NOT NULL AUTO_INCREMENT,
    `PERM`       INTEGER NOT NULL,
    `EMAIL`      VARCHAR(100) UNIQUE NOT NULL,
    `PASSWORD`   VARCHAR(255) NOT NULL,
    `FIRSTNAME`  VARCHAR(30) NOT NULL,
    `LASTNAME`   VARCHAR(30) NOT NULL,
    `STATUS`     INTEGER NOT NULL,
    `REGDATE`    DATE NOT NULL,
    CONSTRAINT `FK_PERS_STAT` FOREIGN KEY (`STATUS`) REFERENCES `STATUS` (`ID`),
    CONSTRAINT `FK_PERS_PERM` FOREIGN KEY (`PERM`) REFERENCES `PERM` (`ID`),
    PRIMARY KEY (`ID`)
    );

CREATE TABLE IF NOT EXISTS `ACCOUNT`
(
    `ID`          BIGINT NOT NULL AUTO_INCREMENT,
    `OWNER`       BIGINT NOT NULL,
    `BALANCE`     DECIMAL(20,2) NOT NULL,
    `STATUS`      INTEGER NOT NULL,
    `REGDATE`     DATE NOT NULL,
    CONSTRAINT `FK_ACC_OWNER` FOREIGN KEY (`OWNER`) REFERENCES `PERSON` (`ID`),
    CONSTRAINT `FK_ACC_STAT` FOREIGN KEY (`STATUS`) REFERENCES `STATUS` (`ID`),
    CONSTRAINT `ACC_POSITIVE_BALANCE` CHECK (`BALANCE` >= 0),
    PRIMARY KEY (`ID`)
    );

CREATE TABLE IF NOT EXISTS `CARDNETWORK`
(
    `ID`     INTEGER NOT NULL,
    `NAME`   VARCHAR(20) NOT NULL,
    PRIMARY KEY (`ID`)
    );

CREATE TABLE IF NOT EXISTS `CARD`
(
    `ID`          BIGINT NOT NULL AUTO_INCREMENT,
    `OWNER`       BIGINT NOT NULL,
    `ACCOUNT`     BIGINT NOT NULL,
    `NETWORK`     INTEGER NOT NULL,
    `CVC`         VARCHAR(255) NOT NULL,
    `STATUS`      INTEGER NOT NULL,
    `EXPDATE`     DATE NOT NULL,
    CONSTRAINT `FK_CARD_OWNER` FOREIGN KEY (`OWNER`) REFERENCES `PERSON` (`ID`),
    CONSTRAINT `FK_CARD_ACC` FOREIGN KEY (`ACCOUNT`) REFERENCES `ACCOUNT` (`ID`),
    CONSTRAINT `FK_CARD_NET` FOREIGN KEY (`NETWORK`) REFERENCES `CARDNETWORK` (`ID`),
    CONSTRAINT `FK_CARD_STAT` FOREIGN KEY (`STATUS`) REFERENCES `STATUS` (`ID`),
    PRIMARY KEY (`ID`)
    );

CREATE TABLE IF NOT EXISTS `INCOME`
(
    `BALANCE`     DECIMAL(20,2) NOT NULL,
    CONSTRAINT `INC_POSITIVE_BALANCE` CHECK (`BALANCE` >= 0)
    );

CREATE TABLE IF NOT EXISTS `PAYMENT`
(
    `ID`          BIGINT NOT NULL AUTO_INCREMENT,
    `AMOUNT`      DECIMAL(20,2) NOT NULL,
    `PAYER`       BIGINT NOT NULL,
    `RECEIVER`    BIGINT NOT NULL,
    `DATE`        DATETIME NOT NULL,
    PRIMARY KEY (`ID`)
    );

CREATE INDEX `I_PRSN_FSTNAME` ON `PERSON` (`FIRSTNAME`);
CREATE INDEX `I_PRSN_LSTNAME` ON `PERSON` (`LASTNAME`);
CREATE INDEX `I_PRSN_REGDATE` ON `PERSON` (`REGDATE`);
CREATE INDEX `I_PRSN_FL_NAME` ON `PERSON` (`FIRSTNAME`, `LASTNAME`);
CREATE INDEX `I_PRSN_LF_NAME` ON `PERSON` (`LASTNAME`, `FIRSTNAME`);
CREATE INDEX `I_PRSN_REGDATE_NAME` ON `PERSON` (`REGDATE`, `LASTNAME`, `FIRSTNAME`);
CREATE INDEX `I_ACC_BALANCE` ON `ACCOUNT` (`BALANCE`);
CREATE INDEX `I_ACC_REGDATE` ON `ACCOUNT` (`REGDATE`);
CREATE INDEX `I_CARD_EXPDATE` ON `CARD` (`EXPDATE`);
CREATE INDEX `I_PAYMNT_AMNT` ON `PAYMENT` (`AMOUNT`);
CREATE INDEX `I_PAYMNT_PYR` ON `PAYMENT` (`PAYER`);
CREATE INDEX `I_PAYMNT_RCVR` ON `PAYMENT` (`RECEIVER`);
CREATE INDEX `I_PAYMNT_DATE` ON `PAYMENT` (`DATE`);

COMMIT;